services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edc-website-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /app/.next
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev
    restart: unless-stopped

volumes:
  node_modules: